# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:         /articles/:year-:month/:title
# Remove relative_permalinks

# Setup
title:               "Changnam"
tagline:             "Developer's Lab"
description:         "프로그래밍에 관하여 글을 쓰는 블로그입니다."
paginate:            5

timezone:          Asia/Seoul
# About/contact
author:
  name:              Changnam Hong
  url:               https://www.github.com/hcn1519
  email:             hcn1519@gmail.com

# Custom vars
version:             1.0.0
