# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:         /articles/:year-:month/:title
url:               "https://hcn1519.github.io" # the base hostname & protocol for your site
baseurl:           ""

imageUrl: "https://hcn1519.github.io/public/postImages"

# Setup
title:               "hcn1519 DEV"
tagline:             "DEV"
description:         "hcn1519 Blog"
paginate:            10

timezone:          Asia/Seoul
# About/contact
author: Changnam Hong

# Custom vars
version:             1.0.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-multiple-languages-plugin

markdown: kramdown
highlighter: rouge

languages: ["ko", "en"]
exclude_from_localizations: ["javascript", "images", "css"]